export const ROTATION_SUBSTITUTIONS: Record<string, string> = {
  "quick ball": "Nest Ball",
  "bola rápida": "Bola Ninho",
  "bola rapida": "Bola Ninho",
  "evolution incense": "Ultra Ball",
  "incenso de evolução": "Ultra Bola",
  "incenso de evolucao": "Ultra Bola",
  "marnie": "Iono",
  "mary": "Iono",
  "marisa": "Iono",
  "escape rope": "Switch",
  "corda de fuga": "Substituição",
  "path to the peak": "Town Store",
  "caminho para o pico": "Loja da Cidade",
  "scoop up net": "Switch",
  "rede de recolhida": "Substituição",
  "professor's letter": "Earthen Vessel",
  "carta do professor": "Recipiente Terrestre",
  "acro bike": "Trekking Shoes",
  "bicicleta acro": "Sapatos de Caminhada",
  "vs seeker": "Pal Pad",
  "pesquisador de vs": "Bloco de Amigos",
};

export const CARD_TRANSLATIONS: Record<string, string> = {
  "professor's research": "pesquisa de professores",
  "professor research": "pesquisa de professores",
  "boss's orders": "ordens do chefe",
  "boss orders": "ordens do chefe",
  "iono": "iono",
  "ultra ball": "ultra bola",
  "nest ball": "bola ninho",
  "buddy-buddy poffin": "poffin amigo",
  "buddy buddy poffin": "poffin amigo",
  "switch": "substituição",
  "super rod": "supercana",
  "earthen vessel": "recipiente terrestre",
  "technical machine: evolution": "máquina técnica: evolução",
  "technical machine evolution": "máquina técnica: evolução",
  "arven": "arven",
  "rare candy": "doce raro",
  "super scoop up": "super recolhida",
  "super potion": "super poção",
  "energy search": "busca de energia",
  "energy retrieval": "recuperação de energia",
  "electric generator": "gerador elétrico",
  "exp. share": "compartilhamento de exp.",
  "exp share": "compartilhamento de exp.",
  "gutsy pickaxe": "picareta audaz",
  "lost vacuum": "vácuo perdido",
  "pokegear 3.0": "pokébola 3.0",
  "pokegear": "pokébola 3.0",
  "nestball": "bola ninho",
  "ultraball": "ultra bola",
  "trekking shoes": "tênis de caminhada",
  "earthenvessel": "recipiente terrestre",
  "town store": "loja da cidade",
  "counter catcher": "pegador de contra-ataque",
  "artazon": "artazon",
  "collapsed stadium": "estádio colapsado",
  "mesagoza": "mesagoza",
  "pokeball": "pokébola",
  "great ball": "grande bola",
  "quick ball": "bola rápida",
  "level ball": "bola de nível",
  "evolution incense": "incenso de evolução",
  "ordinary rod": "vara comum",
  "marnie": "marnie",
  "research": "pesquisa de professores",
  "boss": "ordens do chefe",

  // Energies
  "basic psychic energy": "energia de psíquica básica",
  "basic metal energy": "energia de metal básica",
  "basic fire energy": "energia de fogo básica",
  "basic water energy": "energia de água básica",
  "basic grass energy": "energia de planta básica",
  "basic lightning energy": "energia de raio básica",
  "basic fighting energy": "energia de luta básica",
  "basic darkness energy": "energia de sombria básica",
  "basic dragon energy": "energia de dragão básica",
  "psychic energy": "energia de psíquica básica",
  "metal energy": "energia de metal básica",
  "fire energy": "energia de fogo básica",
  "water energy": "energia de água básica",
  "grass energy": "energia de planta básica",
  "lightning energy": "energia de raio básica",
  "fighting energy": "energia de luta básica",
  "darkness energy": "energia de sombria básica",
  "dragon energy": "energia de dragão básica"
};
